---
title: "MPG vs. other variables in the mtcars dataset"
author: "Manh Cuong"
date: "February 1, 2016"
output: html_document
---

### Project  

- URL: *https://cuong90.shinyapps.io/Shiny_Project/*
- Github Repository: **
- Presentation: 

### Features the application

- The application is used for understanding the relationship between miles per gallon (MPG) and the other variables in the dataset 
- The relationship can be visualised using a box plot as well as a regression model 
- There is a selector using which the user can select the variable that needs to be used for the comparison 
- Also the user has the flexibility to show the outliers or to hide them in the analysis 
- The outliers check box is applicable only to the box plot and all outliers are always included in the regression model 
- The user can toggle between the box plot and the regression model by clicking on the appropriate tabs

### Run the application

- Method 1: Run on web brower by accessing link: *https://cuong90.shinyapps.io/Shiny_Project/*
- Method 2: Using Rstudio. Firstly, download the source code from github. Change working directory to the folder containing the source code. Then, run the application by command "library(shiny);runApp()"
